### PR TITLE
Attempt to update Connexion library to version 3

### PR DESCRIPTION
**Pull request by VladaZakharova**
---
**^ Add meaningful description above**
Read the **[Pull Request Guidelines](https://github.com/apache/airflow/blob/main/CONTRIBUTING.rst#pull-request-guidelines)** for more information.
In case of fundamental code changes, an Airflow Improvement Proposal ([AIP](https://cwiki.apache.org/confluence/display/AIRFLOW/Airflow+Improvement+Proposals)) is needed.
In case of a new dependency, check compliance with the [ASF 3rd Party License Policy](https://www.apache.org/legal/resolved.html#category-x).
In case of backwards incompatible changes please leave a note in a newsfragment file, named `{pr_number}.significant.rst` or `{issue_number}.significant.rst`, in [newsfragments](https://github.com/apache/airflow/tree/main/newsfragments).

### CODE REVIEW

**Comment by VladaZakharova** [comment]
@RobbeSneyders

**Comment by potiuk** [comment]
I think @vincbeck will be better to comment :)

**Comment by RobbeSneyders** [comment]
Hi @VladaZakharova, I need to find some time to look at this, will try to do so in the coming week. 

FYI, I already started porting this myself 2 weeks ago, but didn't have the time to complete it. It should give me a better understanding to review though.

**Comment by VladaZakharova** [comment]
> I think @vincbeck will be better to comment :)

Thank you :)
I would appreciate any help!

**Comment by VladaZakharova** [comment]
> Hi @VladaZakharova, I need to find some time to look at this, will try to do so in the coming week.
> 
> FYI, I already started porting this myself 2 weeks ago, but didn't have the time to complete it. It should give me a better understanding to review though.

Thank you!
Honestly, there are not a lot of changes right now, but i would appreciate any help and any new ideas :D

**Comment by vincbeck** [comment]
Hey @VladaZakharova . Happy to help!

> The problem that i have faced is trying to update this class will lead to errors on the users side who actually use this class with FlaskApi return type from method get_api_endpoints()

You should not worry about that, as of today nobody uses this class (implementation is not done yet), thus, changing some method signature is not breaking change

> Jarek, am i right about authentication manager here? We should consider finding some other solution here instead of changing the implementation other way round for this class? :)

The overall direction of the change looks good to me and this is exactly what I had in mind

You successfully updated the signature of `get_api_endpoints` but you did not modify the consumer which is [here](https://github.com/apache/airflow/blob/main/airflow/www/extensions/init_views.py#L332). You should do that. Other than that, it looks pretty good to me!

**Comment by potiuk** [comment]
Yep. looks Cool. Can you please rebase it / resolve conflicts as well @VladaZakharova ? I want to see how/if connexion 3 is used in the resulting image and maybe then we will also get @RobbeSneyders expert glance to see if all is fine :)

**Pull request closed without merging**
