### PR TITLE
Fix Vertex AI Auto ML tests

### PR DESCRIPTION
**Pull request by MaksYermak**
---
**^ Add meaningful description above**
Read the **[Pull Request Guidelines](https://github.com/apache/airflow/blob/main/CONTRIBUTING.rst#pull-request-guidelines)** for more information.
In case of fundamental code changes, an Airflow Improvement Proposal ([AIP](https://cwiki.apache.org/confluence/display/AIRFLOW/Airflow+Improvement+Proposals)) is needed.
In case of a new dependency, check compliance with the [ASF 3rd Party License Policy](https://www.apache.org/legal/resolved.html#category-x).
In case of backwards incompatible changes please leave a note in a newsfragment file, named `{pr_number}.significant.rst` or `{issue_number}.significant.rst`, in [newsfragments](https://github.com/apache/airflow/tree/main/newsfragments).

### CODE REVIEW

**Review by moiseenkov — COMMENTED** [review]
- DAG_IDs should be unique in each test because they run in parallel and might conflict
-  Is it possible to use our public bucket `airflow-system-tests-resources` directly without copying files into another one?

**Comment by MaksYermak** [comment]
> * DAG_IDs should be unique in each test because they run in parallel and might conflict
> * Is it possible to use our public bucket `airflow-system-tests-resources` directly without copying files into another one?

* Sorry, could you please explain what you mean? Because, I use a unique name for each DAG:
https://github.com/lwyszomi/airflow/pull/141/files#diff-c2cfb4c259c51de4f826165bfd919a5d7f1881ac4245c4a11f1b3da052977923R87
https://github.com/lwyszomi/airflow/pull/141/files#diff-8962d9b166a1cb6c5b8abb787ecc7d6ddfe3006880ee5766762d70440a1e6fffR74
https://github.com/lwyszomi/airflow/pull/141/files#diff-3f26b909c0e2371d3ab8ae6de0b0608804ebb22b425935c93638cd707756a03aR89
https://github.com/lwyszomi/airflow/pull/141/files#diff-154e6c804cd80d7ce84e8be61a60d07d18bccac5ef31021a7b79212bc7542bc9R73
https://github.com/lwyszomi/airflow/pull/141/files#diff-f764f5db413ae1eae037c10179f03b108a6f7de28ad227b872cb4f6055fc19e3R73

* No, we need to use a bucket with a specific location and storage class

**Comment by moiseenkov** [comment]
> 

Oh, I didn't notice that because I just got used to seeing unique DAG_ID at the top of the module. Do you think we could stick to that general approach here too? It's only matter of style consistency, not critical though.

**Comment by MaksYermak** [comment]
> > 
> 
> Oh, I didn't notice that because I just got used to seeing unique DAG_ID at the top of the module. Do you think we could stick to that general approach here too? It's only matter of style consistency, not critical though.

I use this approach, because we use DAG_ID like a part of bucket_name and with our general approach the bucket_name starts to be long to create a bucket.

**Comment by moiseenkov** [comment]
> 

I see now. thanks for clarifying!

**Pull request closed without merging**
